language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t razatg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true razatg/react-test npm test

after_success:
  - docker build -t razatg/multi-client ./client
  - docker build -t razatg/multi-nginx ./nginx
  - docker build -t razatg/multi-server ./server
  - docker build -t razatg/multi-worker ./worker
# log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push these images to docker hub
  - docker push razatg/multi-client
  - docker push razatg/multi-nginx
  - docker push razatg/multi-server
  - docker push razatg/multi-worker